# Copiar este archivo a:  .streamlit/secrets.toml
# (crear la carpeta .streamlit junto a app.py)

[postgres]
host = "localhost"
port = 5432
user = "postgres"
password = "TU_CONTRASEÑA"
database = "postgres"
